FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8001
ENV USER_SERVICE_URL=http://localhost:8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"] 